#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# OS is set in stage 1 and read by ensure_cmd: "mac" or "ubuntu".
OS=""
INSTALLED=()  # commands this run actually installed
PRESENT=()    # commands already present, skipped
LOGIN_SHELL_CHANGED=0  # set to 1 if this run ran chsh to zsh
OMT_DIR="$HOME/.local/share/oh-my-tmux"  # oh-my-tmux clone (stage 4 + stage 8)

# intro is this wizard's opening frame. (The library's banner() talks about
# browsers and copied values, which don't apply to a package installer.)
intro() {
  _clear
  printf '\n%s%s  Dotfiles bootstrap%s\n' "$BOLD" "$BLUE" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Installs the tools this dotfiles repo needs, one at a time. Anything\n' "$DIM"
  printf '  already installed is detected and skipped, so it is safe to re-run.%s\n' "$RESET"
  pause "Ready to start?"
}

# ensure_cmd CMD [BREW_PKG] [APT_PKG] installs CMD unless it is already on
# PATH. Package names default to CMD when the extra args are omitted.
ensure_cmd() {
  local cmd="$1" brew_pkg="${2:-$1}" apt_pkg="${3:-$1}"
  if command -v "$cmd" >/dev/null 2>&1; then
    note "$cmd already installed ($(command -v "$cmd")) — skipping"
    PRESENT+=("$cmd")
    return 0
  fi
  if [[ "$OS" == mac ]]; then
    step "installing $cmd with: brew install $brew_pkg"
    brew install "$brew_pkg"
  else
    step "installing $cmd with: sudo apt-get install -y $apt_pkg"
    sudo apt-get install -y "$apt_pkg"
  fi
  printf '  %s✓ installed%s %s\n' "$GREEN" "$RESET" "$cmd"
  INSTALLED+=("$cmd")
}

# prep_config_dir DIR NAME makes DIR a real, empty directory so that later
# `stow NAME` links files into it, rather than folding the whole directory
# into a single symlink. If DIR already exists, offer to delete it so stow
# rebuilds from a clean slate. Always returns 0.
prep_config_dir() {
  local dir="$1" name="$2"
  if [[ ! -e "$dir" ]]; then
    step "creating empty $dir for 'stow $name'"
    mkdir -p "$dir"
    return 0
  fi
  warn "$dir already exists."
  say "Deleting it lets 'stow $name' recreate its contents as clean symlinks"
  say "from ~/dotfiles. Anything in there that is not tracked in ~/dotfiles is lost."
  if confirm "delete $dir and let stow rebuild it?"; then
    [[ -n "$HOME" && "$dir" == "$HOME/"* ]] && rm -rf "$dir"
    mkdir -p "$dir"
    say "cleared."
  else
    say "keeping it; 'stow $name' may report conflicts for you to resolve by hand."
  fi
  return 0
}

intro

# ── Stage 1: which OS ─────────────────────────────────────────────────────
stage "Which machine is this?"

# Auto-detect from uname, then let the human confirm or override.
case "$(uname -s)" in
  Darwin) OS="mac" ;;
  Linux)  OS="ubuntu" ;;
  *)      OS="" ;;
esac
[[ -n "$OS" ]] && note "detected: $OS"

ask OS_CHOICE "OS — type 'mac' or 'ubuntu'${OS:+ [Enter for $OS]}:"
[[ -z "$OS_CHOICE" && -n "$OS" ]] && OS_CHOICE="$OS"
case "$OS_CHOICE" in
  mac|Mac|macos|macOS|darwin)     OS="mac" ;;
  ubuntu|Ubuntu|linux|Linux|deb)  OS="ubuntu" ;;
  *) warn "unrecognised: '$OS_CHOICE' — expected 'mac' or 'ubuntu'"; exit 1 ;;
esac
say "using: $OS"

if [[ "$OS" == mac ]]; then
  if ! command -v brew >/dev/null 2>&1; then
    warn "Homebrew not found. Install it first: https://brew.sh"
    exit 1
  fi
else
  say "apt needs sudo. You'll enter your password once now; it's cached for the"
  say "rest of this run (about 15 minutes), so later steps won't re-prompt."
  sudo -v
  step "refreshing the apt package index: sudo apt-get update"
  sudo apt-get update
fi

# ── Stage 2: stow ────────────────────────────────────────────────────────
stage "GNU Stow"
say "Stow is the symlink manager that puts these dotfiles into place."
ensure_cmd stow

# ── Stage 3: zsh ─────────────────────────────────────────────────────────
stage "zsh"
say "The shell config in this repo is written for zsh."
ensure_cmd zsh

zsh_path="$(command -v zsh || true)"
if [[ -n "$zsh_path" && "${SHELL:-}" != "$zsh_path" ]]; then
  note "your login shell is currently: ${SHELL:-unknown}"
  if confirm "make zsh your login shell (chsh -s $zsh_path)?"; then
    if ! grep -qxF "$zsh_path" /etc/shells 2>/dev/null; then
      step "registering $zsh_path in /etc/shells"
      echo "$zsh_path" | sudo tee -a /etc/shells >/dev/null
    fi
    chsh -s "$zsh_path"
    LOGIN_SHELL_CHANGED=1
    say "done. See the note at the end about making it take effect."
  else
    SKIPPED+=("set zsh as login shell: chsh -s $zsh_path")
  fi
fi

# ── Stage 4: tmux ────────────────────────────────────────────────────────
stage "tmux"
say "Terminal multiplexer. The 'tmux' package name is the same on brew and apt."
ensure_cmd tmux

# oh-my-tmux ships .tmux.conf (linked into place in stage 8) plus a
# .tmux.conf.local for personal overrides. Clone it now; the ~/.config/tmux
# directory and the tmux.conf symlink are set up in stage 8, and
# tmux.conf.local is stowed from ~/dotfiles.
if [[ -d "$OMT_DIR" ]]; then
  note "oh-my-tmux already cloned at $OMT_DIR — skipping"
else
  step "git clone https://github.com/gpakosz/.tmux.git ~/.local/share/oh-my-tmux"
  git clone https://github.com/gpakosz/.tmux.git "$OMT_DIR"
fi

# ── Stage 5: neovim ──────────────────────────────────────────────────────
stage "neovim"
say "The command is 'nvim' but the package is 'neovim' on both brew and apt."
ensure_cmd nvim neovim neovim

# ── Stage 6: LazyVim dependencies ────────────────────────────────────────
stage "LazyVim dependencies"
say "LazyVim needs three extra tools:"
say "  - curl            (blink.cmp downloads its fuzzy-matching library)"
say "  - a C compiler     (nvim-treesitter, main branch, builds parsers)"
say "  - the tree-sitter CLI (nvim-treesitter, main branch, drives the build)"

ensure_cmd curl

# C compiler: test an actual compile (compiler + headers + linker), not just
# whether the 'cc' symlink exists.
if printf '#include <stdio.h>\nint main(void){return 0;}\n' | cc -x c -o /dev/null - 2>/dev/null; then
  note "C compiler works ($(command -v cc)) — skipping"
  PRESENT+=("C compiler")
elif [[ "$OS" == mac ]]; then
  step "installing the Xcode Command Line Tools: xcode-select --install"
  xcode-select --install 2>/dev/null || true
  warn "finish the install dialog that just opened, then re-run this script"
  SKIPPED+=("C compiler: complete 'xcode-select --install', then re-run")
else
  step "installing a C toolchain: sudo apt-get install -y build-essential"
  sudo apt-get install -y build-essential
  INSTALLED+=("build-essential")
fi

# tree-sitter CLI: the package is 'tree-sitter-cli' on both apt and brew
# (brew's plain 'tree-sitter' is the library only). The binary is 'tree-sitter'.
ensure_cmd tree-sitter tree-sitter-cli tree-sitter-cli

# ── Stage 7: kitty ───────────────────────────────────────────────────────
stage "kitty"
say "kitty ships an official binary installer that's identical on mac and Linux."
say "It installs to /Applications/kitty.app (mac) or ~/.local/kitty.app (Linux)"
say "and touches nothing else. Re-running it updates kitty in place."

if command -v kitty >/dev/null 2>&1 \
  || [[ -e "$HOME/.local/kitty.app/bin/kitty" || -d "/Applications/kitty.app" ]]; then
  note "kitty already installed — skipping (re-run the installer any time to update)"
  PRESENT+=("kitty")
else
  step "installing kitty: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin"
  if confirm "run the kitty installer now?"; then
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    INSTALLED+=("kitty")
    note "installed to ~/.local/kitty.app — putting it on PATH is a later step."
  else
    SKIPPED+=("install kitty: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin")
  fi
fi

# ── Stage 8: eza ─────────────────────────────────────────────────────────
stage "eza"
say "Modern ls replacement. Package name is 'eza' on both brew and apt."
ensure_cmd eza

# ── Stage 9: prepare config directories ──────────────────────────────────
stage "prepare config directories"
say "stow links files into a directory. If ~/.config/<tool> is missing, stow"
say "would replace the whole directory with a single symlink ('folding'), which"
say "traps anything the app later writes there inside ~/dotfiles."
say "Each directory is made real and empty here so that never happens. An"
say "existing one can be deleted so stow rebuilds it clean."

prep_config_dir "$HOME/.config/kitty" kitty
prep_config_dir "$HOME/.config/nvim"  nvim
prep_config_dir "$HOME/.config/tmux"  tmux
prep_config_dir "$HOME/.config/eza"   eza

# tmux only: stow owns tmux.conf.local; tmux.conf is a link into the clone.
if [[ -d "$OMT_DIR" ]]; then
  step "link ~/.config/tmux/tmux.conf -> oh-my-tmux/.tmux.conf"
  ln -sf "$OMT_DIR/.tmux.conf" "$HOME/.config/tmux/tmux.conf"
fi

# ── Summary ──────────────────────────────────────────────────────────────
_clear
printf '\n%s%s  ✓ Bootstrap complete%s\n' "$BOLD" "$GREEN" "$RESET"
(( ${#INSTALLED[@]} )) && note "installed: ${INSTALLED[*]}"
(( ${#PRESENT[@]} ))   && note "already present: ${PRESENT[*]}"
if (( ${#SKIPPED[@]} )); then
  printf '\n'; warn "still to do by hand:"
  for s in "${SKIPPED[@]}"; do note "  - $s"; done
fi

if (( LOGIN_SHELL_CHANGED )); then
  printf '\n'
  warn "zsh is now your login shell, but this session and new terminal tabs"
  warn "still run your old shell. To switch over:"
  if [[ "$OS" == mac ]]; then
    note "  quit the terminal app completely and reopen it (or log out and back in)"
  else
    note "  log all the way out of your desktop session and back in"
  fi
fi

printf '\n'
note "next: cd ~/dotfiles && make"
printf '\n'
